#!/bin/sh

. /opt/wz_mini/wz_mini.conf
. /opt/wz_mini/etc/rc.common

echo "Store dmesg logs"

DMESG_LOG=/opt/wz_mini/log/dmesg
rotate_log "$DMESG_LOG"
dmesg > $DMESG_LOG.log 2>&1

echo "Deleting logs older than 5 boots..."

find /opt/wz_mini/log -name '*log*' | while read file; do
[ "${file#/opt/wz_mini/log/*log.}" -gt 5 ] && rm -v "$file"
done
