#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Short-Description: Store syslogs
# Description:       Enable storing of syslogs to media
### END INIT INFO

. /opt/wz_mini/etc/rc.common
. /opt/wz_mini/wz_mini.conf

syslog_save() {
	wait_for_icamera

	echo "#####$(basename "$0")#####"

	if [[ "$ENABLE_SYSLOG_SAVE" == "true" ]]; then
		echo "Store syslog logs"

		SYSLOG_LOG=/opt/wz_mini/log/syslog
		rotate_log "$SYSLOG_LOG"
		logread -F > $SYSLOG_LOG.log &
	fi

}

case "$1" in
	start)
		syslog_save &
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

